---
- name: Add grafana repository
  yum_repository:
    name: grafana
    description: "Grafana Repository RHEL"
    baseurl: https://packagecloud.io/grafana/stable/el/6/$basearch
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    gpgcheck: yes
    
- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Install Grafana package for RedHat
  yum:
    name: "{{ grafana_pkg }}"
    state: present
  notify:
    - Restart grafana
  tags:
    - grafana_pkg

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart grafana
  tags:
    - grafana_config

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/sbin/grafana-server | grep cap_net_bind_service
  register: grafana_bind_cap
  failed_when: False
  changed_when: False
  when: grafana_allow_low_port
  tags:
    - grafana_config

- name: Set capability on the binary file to be able to bind to TCP port <1024
  shell: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
  when: grafana_allow_low_port and grafana_bind_cap.rc > 0
  notify:
    - Restart grafana
  tags:
    - grafana_config

- name: Make sure grafana service is enabled and running
  service:
    name: grafana-server
    enabled: yes
    state: running
